id = "deps"
name = "Deps"
description = "Intelligent dependency insights across package ecosystems"
version = "0.1.1"
schema_version = 1
authors = ["Andrei G"]
repository = "https://github.com/bug-ops/deps-lsp"

[language_servers.deps-lsp]
name = "Deps LSP"
languages = ["TOML", "JSON", "Go Mod", "Ruby"]

[language_servers.deps-lsp.language_ids]
"TOML" = "toml"
"JSON" = "json"
"Go Mod" = "gomod"
"Ruby" = "ruby"
