id = "deps-language-server"
name = "Deps"
description = "Dependency management LSP with lock file support"
version = "0.1.0"
schema_version = 1
authors = ["Andrei G <k05h31@gmail.com>"]
repository = "https://github.com/bug-ops/deps-lsp"

[language_servers.deps-lsp]
name = "Deps LSP"
languages = ["TOML", "JSON"]
