id = "deps-language-server"
name = "Deps"
description = "Intelligent dependency insights across package ecosystems"
version = "0.1.3"
schema_version = 1
authors = ["Andrei G <k05h31@gmail.com>"]
repository = "https://github.com/bug-ops/deps-lsp"

[language_servers.deps-lsp]
name = "Deps LSP"
languages = ["TOML", "JSON", "Go Mod", "Ruby", "Dart"]

[language_servers.deps-lsp.language_ids]
"TOML" = "toml"
"JSON" = "json"
"Go Mod" = "gomod"
"Ruby" = "ruby"
"Dart" = "dart"
